name: Daily Automated Commits

on:
  schedule:
    # Runs every day at 09:00 UTC (9 AM)
    - cron: '35 5 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make daily update
        run: |
          if [ ! -f daily_log.md ]; then
            echo "# Daily Commit Log" > daily_log.md
          fi
          echo "- $(date '+%Y-%m-%d %H:%M:%S')" >> daily_log.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Dhruvil-Tarpara"
          author_email: "dhruviltarpara99@gmail.com"
          message: "Daily automated commit"
          add: daily_log.md
          push: true
